name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          mkdir -p PDF
          echo; echo "Input Folder Listing"
          ls
          echo; echo "Generating PDF"
          cat "Guia de seguridad de dispositivos.md" | md-to-pdf > "PDF/Guia de seguridad de dispositivos.pdf"
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: PDF
