name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          mkdir -p PDF
          echo; echo "Generating PDF"
          cat "Guia de seguridad de dispositivos.md" | md-to-pdf --highlight-style='github' --md-file-encoding='utf-8' --pdf-options '{ "format": "A4", "margin": "10mm", "printBackground": true, "preferCSSPageSize": true } > "PDF/Guia de seguridad de dispositivos.pdf"  
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: PDF

      - name: Create a release
        uses: action-pack/github-release@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: MyReleaseTag
          title: MyReleaseTitle
          body: MyReleaseMessage
          
